export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const LOAD_PASSENGERS_SUCCESS = "LOAD_PASSENGERS_SUCCESS";
export const LOAD_PASSENGERS_LOOKUP_SUCCESS = "LOAD_PASSENGERS_LOOKUP_SUCCESS";
export const CREATE_PASSENGER_SUCCESS = "CREATE_PASSENGER_SUCCESS";
export const UPDATE_PASSENGER_SUCCESS = "UPDATE_PASSENGER_SUCCESS";
export const DELETE_PASSENGER_OPTIMISTIC = "DELETE_PASSENGER_OPTIMISTIC";

export const LOAD_CHECKIN_PASSENGERS_SUCCESS =
  "LOAD_CHECKIN_PASSENGERS_SUCCESS";
export const CREATE_CHECKIN_PASSENGER_SUCCESS =
  "CREATE_CHECKIN_PASSENGER_SUCCESS";
export const UPDATE_CHECKIN_PASSENGER_SUCCESS =
  "UPDATE_CHECKIN_PASSENGER_SUCCESS";
export const DELETE_CHECKIN_PASSENGER_OPTIMISTIC =
  "DELETE_CHECKIN_PASSENGER_OPTIMISTIC";

export const LOAD_FLIGHT_SERVICES_SUCCESS = "LOAD_FLIGHT_SERVICES_SUCCESS";
export const LOAD_FLIGHT_SERVICES_LOOKUP_SUCCESS =
  "LOAD_FLIGHT_SERVICES_LOOKUP_SUCCESS";
export const CREATE_FLIGHT_SERVICE_SUCCESS = "CREATE_FLIGHT_SERVICE_SUCCESS";
export const UPDATE_FLIGHT_SERVICE_SUCCESS = "UPDATE_FLIGHT_SERVICE_SUCCESS";
export const DELETE_FLIGHT_SERVICE_OPTIMISTIC =
  "DELETE_FLIGHT_SERVICE_OPTIMISTIC";

export const LOAD_FLIGHTS_SUCCESS = "LOAD_FLIGHTS_SUCCESS";
export const LOAD_FLIGHTS_DETAIL_SUCCESS = "LOAD_FLIGHTS_DETAIL_SUCCESS";
export const LOAD_SEAT_DETAILS_SUCCESS = "LOAD_SEAT_DETAILS_SUCCESS";
export const CREATE_SEAT_DETAILS_SUCCESS = "CREATE_SEAT_DETAILS_SUCCESS";
export const UPDATE_SEAT_DETAILS_SUCCESS = "UPDATE_SEAT_DETAILS_SUCCESS";

export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
