const passengers = [
  {
    id: 1,
    name: "Ragu Ram A",
    wheelchairRequired: true,
    infants: false,
    ancillaryServices: "baggage",
    seatNo: "1A",
    specialMeal: "Dosa",
    inflightShop: "Iphone",
    passport: "AXX12XXX",
    address: "Mangalore",
    dob: "2014-01-01",
    fid: 12233,
    hovered: false,
    checkedIn: true,
  },
  {
    id: 2,
    name: "Samson",
    checkedIn: false,
    wheelchairRequired: false,
    infants: true,
    ancillaryServices: "wifi",
    seatNo: "1B",
    specialMeal: "Dosa",
    inflightShop: "Iphone",
    passport: "",
    address: "Delhi",
    dob: "",
    fid: 12233,
    hovered: false,
  },
  {
    id: 3,
    name: "Steve",
    checkedIn: false,
    wheelchairRequired: false,
    infants: true,
    ancillaryServices: "Car Service",
    seatNo: "2A",
    specialMeal: "true",
    inflightShop: "Iphone",
    passport: "BXX12XXX",
    address: "",
    dob: "2014-01-01",
    fid: 12233,
    hovered: false,
  },
  {
    id: 4,
    name: "Ramesh Kumar",
    checkedIn: true,
    wheelchairRequired: true,
    infants: false,
    ancillaryServices: "baggage",
    seatNo: "4C",
    specialMeal: "true",
    inflightShop: "",
    passport: "BXX12XXX",
    address: "WB",
    dob: "2014-01-01",
    fid: 13322,
    hovered: false,
  },
  {
    id: 5,
    name: "Yathi",
    checkedIn: true,
    wheelchairRequired: false,
    infants: false,
    ancillaryServices: "baggage",
    specialMeal: "true",
    inflightShop: "Headphone",
    passport: "",
    seatNo: "4D",
    address: "Mangalore",
    dob: "2014-01-01",
    fid: 13322,
    hovered: false,
  },
  {
    id: 6,
    name: "Prabhu",
    checkedIn: true,
    wheelchairRequired: false,
    infants: false,
    ancillaryServices: "baggage",
    seatNo: "3A",
    specialMeal: "true",
    inflightShop: "",
    passport: "BXX12XXX",
    address: "",
    dob: "2014-01-01",
    fid: 13322,
    hovered: false,
  },
  {
    id: 7,
    name: "Prem",
    checkedIn: true,
    wheelchairRequired: false,
    infants: false,
    ancillaryServices: "baggage",
    seatNo: "1A",
    specialMeal: "true",
    inflightShop: "",
    passport: "BXX12XXX",
    address: "MH",
    dob: "2014-01-01",
    fid: 13322,
    hovered: false,
  },
  {
    id: 8,
    name: "ABD",
    checkedIn: true,
    wheelchairRequired: false,
    infants: false,
    ancillaryServices: "",
    seatNo: "3D",
    specialMeal: "",
    inflightShop: "",
    passport: "BXX12XXX",
    address: "Mangalore",
    dob: "",
    fid: 12233,
    hovered: false,
  },
  {
    id: 9,
    name: "Raj",
    checkedIn: true,
    wheelchairRequired: false,
    infants: false,
    ancillaryServices: "Wifi",
    seatNo: "2D",
    specialMeal: "Idli",
    inflightShop: "Oneplus",
    passport: "BXX12XXX",
    address: "Mysore",
    dob: "",
    fid: 13322,
    hovered: false,
  },
  {
    id: 10,
    name: "munna",
    checkedIn: true,
    wheelchairRequired: false,
    infants: false,
    ancillaryServices: "baggage",
    seatNo: "3C",
    specialMeal: "false",
    inflightShop: "",
    passport: "BXX12XXX",
    address: "kashmir",
    dob: "",
    fid: 13322,
    hovered: false,
  },
];

const checkInPassengers = [
  {
    name: "Micky",
    passport: "J12393496",
    address: "Bangalore",
    dob: "1990-03-19T15:49:02.111Z",
    weelchair: false,
    infant: true,
    specialMeals: true,
    flight: "1",
    seatno: "A1",
    id: 1,
    createdAt: 1591537024592,
  },
  {
    name: "John",
    passport: "ABA9875413",
    address: "Bangalore",
    dob: "1994-08-11T14:29:17.746Z",
    infant: true,
    specialMeals: true,
    flight: "1",
    seatno: "B1",
    id: 2,
    createdAt: 1591537068140,
  },
  {
    name: "Kevin",
    passport: "KF0192332C",
    address: "Bangalore",
    dob: "2000-09-29T16:45:22.000Z",
    infant: false,
    specialMeals: true,
    flight: "1",
    seatno: "C1",
    id: 3,
    createdAt: 1591537102167,
  },
  {
    name: "Russell",
    passport: "KF0188312C",
    address: "Bangalore",
    dob: "2011-11-19T18:48:13.000Z",
    flight: "1",
    seatno: "A2",
    id: 4,
    createdAt: 1591537137376,
  },
];

const flights = [
  {
    id: 12233,
    scheduleDate: "2023-04-13",
    time: "23:28:56",
    source: "BLR",
    destination: "DEL",
  },
  {
    id: 13322,
    scheduleDate: "2023-04-13",
    time: "23:28:56",
    source: "CCU",
    destination: "BLR",
  },
  {
    id: 12234,
    scheduleDate: "2023-04-13",
    time: "23:28:56",
    source: "HBX",
    destination: "DEL",
  },
  {
    scheduleDate: "2023-04-13",
    time: "23:28:56",
    source: "HBX",
    destination: "DEL",
    id: 13323,
  },
  {
    scheduleDate: "2023-04-13",
    time: "23:28:56",
    source: "IXE",
    destination: "HBX",
    id: 13324,
  },
];

const seats = [
  {
    id: 12233,
    seat: [
      {
        id: "1A",
        flightId: 12233,
        checkedIn: true,
        wheelchairRequired: true,
        infants: false,
        specialMeal: true,
        isAvailable: false,
      },
      {
        id: "1B",
        flightId: 12233,
        checkedIn: false,
        wheelchairRequired: false,
        infants: true,
        specialMeal: true,
        isAvailable: false,
      },
      {
        id: "1C",
        flightId: 12233,
        checkedIn: false,
        wheelchairRequired: false,
        infants: false,
        specialMeal: false,
        isAvailable: true,
      },
      {
        id: "1D",
        flightId: 12233,
        checkedIn: false,
        wheelchairRequired: false,
        infants: false,
        specialMeal: false,
        isAvailable: true,
      },
      {
        id: "2A",
        flightId: 12233,
        checkedIn: false,
        wheelchairRequired: false,
        infants: true,
        specialMeal: true,
        isAvailable: false,
      },
      {
        id: "2B",
        flightId: 12233,
        checkedIn: false,
        wheelchairRequired: false,
        infants: false,
        specialMeal: false,
        isAvailable: true,
      },
      {
        id: "2C",
        flightId: 12233,
        checkedIn: false,
        wheelchairRequired: false,
        infants: false,
        specialMeal: false,
        isAvailable: true,
      },
      {
        id: "2D",
        flightId: 12233,
        checkedIn: false,
        wheelchairRequired: false,
        infants: false,
        specialMeal: false,
        isAvailable: true,
      },
      {
        id: "3A",
        flightId: 12233,
        checkedIn: false,
        wheelchairRequired: false,
        infants: false,
        specialMeal: false,
        isAvailable: true,
      },
      {
        id: "3B",
        flightId: 12233,
        checkedIn: false,
        wheelchairRequired: false,
        infants: false,
        specialMeal: false,
        isAvailable: true,
      },
      {
        id: "3C",
        flightId: 12233,
        checkedIn: false,
        wheelchairRequired: false,
        infants: false,
        specialMeal: false,
        isAvailable: true,
      },
      {
        id: "3D",
        flightId: 12233,
        checkedIn: true,
        wheelchairRequired: true,
        infants: false,
        specialMeal: false,
        isAvailable: false,
      },
      {
        id: "4A",
        flightId: 12233,
        checkedIn: false,
        wheelchairRequired: false,
        infants: false,
        specialMeal: false,
        isAvailable: true,
      },
      {
        id: "4B",
        flightId: 12233,
        checkedIn: false,
        wheelchairRequired: false,
        infants: false,
        specialMeal: false,
        isAvailable: true,
      },
      {
        id: "4C",
        flightId: 12233,
        checkedIn: false,
        wheelchairRequired: false,
        infants: false,
        specialMeal: false,
        isAvailable: true,
      },
      {
        id: "4D",
        flightId: 12233,
        checkedIn: false,
        wheelchairRequired: false,
        infants: false,
        specialMeal: false,
        isAvailable: true,
      },
    ],
  },
  {
    id: 13322,
    seat: [
      {
        id: "1A",
        flightId: 13322,
        checkedIn: true,
        wheelchairRequired: false,
        infants: false,
        specialMeal: true,
        isAvailable: false,
      },
      {
        id: "1B",
        flightId: 13322,
        checkedIn: false,
        wheelchairRequired: false,
        infants: false,
        specialMeal: false,
        isAvailable: true,
      },
      {
        id: "1C",
        flightId: 13322,
        checkedIn: false,
        wheelchairRequired: false,
        infants: false,
        specialMeal: false,
        isAvailable: true,
      },
      {
        id: "1D",
        flightId: 13322,
        checkedIn: false,
        wheelchairRequired: false,
        infants: false,
        specialMeal: false,
        isAvailable: true,
      },
      {
        id: "2A",
        flightId: 13322,
        checkedIn: false,
        wheelchairRequired: false,
        infants: false,
        specialMeal: false,
        isAvailable: true,
      },
      {
        id: "2B",
        flightId: 13322,
        checkedIn: false,
        wheelchairRequired: false,
        infants: false,
        specialMeal: false,
        isAvailable: true,
      },
      {
        id: "2C",
        flightId: 13322,
        checkedIn: false,
        wheelchairRequired: false,
        infants: false,
        specialMeal: false,
        isAvailable: true,
      },
      {
        id: "2D",
        flightId: 13322,
        checkedIn: true,
        wheelchairRequired: false,
        infants: false,
        specialMeal: true,
        isAvailable: false,
      },
      {
        id: "3A",
        flightId: 13322,
        checkedIn: true,
        wheelchairRequired: false,
        infants: false,
        specialMeal: true,
        isAvailable: false,
      },
      {
        id: "3B",
        flightId: 13322,
        checkedIn: false,
        wheelchairRequired: false,
        infants: false,
        specialMeal: false,
        isAvailable: true,
      },
      {
        id: "3C",
        flightId: 13322,
        checkedIn: true,
        wheelchairRequired: false,
        infants: false,
        specialMeal: false,
        isAvailable: false,
      },
      {
        id: "3D",
        flightId: 13322,
        checkedIn: false,
        wheelchairRequired: false,
        infants: false,
        specialMeal: false,
        isAvailable: true,
      },
      {
        id: "4A",
        flightId: 13322,
        checkedIn: false,
        wheelchairRequired: false,
        infants: false,
        specialMeal: false,
        isAvailable: true,
      },
      {
        id: "4B",
        flightId: 13322,
        checkedIn: false,
        wheelchairRequired: false,
        infants: false,
        specialMeal: false,
        isAvailable: true,
      },
      {
        id: "4C",
        flightId: 13322,
        checkedIn: true,
        wheelchairRequired: true,
        infants: false,
        specialMeal: true,
        isAvailable: false,
      },
      {
        id: "4D",
        flightId: 13322,
        checkedIn: true,
        wheelchairRequired: false,
        infants: false,
        specialMeal: true,
        isAvailable: false,
      },
    ],
  },
];

const services = [
  {
    id: 1,
    fid: 12233,
    ancillaryServices: ["baggage", "wifi"],
    inflightShop: ["Iphone", "Oneplus"],
    specialMeal: ["Dosa"],
  },
  {
    id: 2,
    fid: 13322,
    ancillaryServices: ["Wifi", "baggage"],
    inflightShop: ["Oneplus", "Nikon"],
    specialMeal: ["Dosa"],
  },
];

// Using CommonJS style export so we can consume via Node (without using Babel-node)
module.exports = {
  passengers,
  checkInPassengers,
  flights,
  seats,
  services,
};
